name: Claude Assistant

on:
  issue_comment:
    types: [created]
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [opened]

jobs:
  claude-response:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'pull_request' && github.event.action == 'opened')
    
    steps:
    - uses: anthropics/claude-code-action@beta
      with:
        anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        trigger_phrase: "@claude"
        custom_instructions: |
          You are reviewing code for the omnicost project, a multi-cloud cost report CLI.
          When a PR is opened, automatically review the changes and provide feedback on:
          1. Code quality and TypeScript best practices
          2. Potential bugs or issues
          3. Performance considerations
          4. Security concerns
          5. Consistency with the project architecture and patterns
          
          Be concise and focus on actionable feedback.
