name: Claude Code Assist

on:
  issue_comment:
    types: [created]

jobs:
  claude-assist:
    if: |
      github.event.issue.pull_request && 
      contains(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    
    - name: Process Claude request
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: |
        # Install Claude Code CLI
        npm install -g @anthropic/claude-code
        
        # Extract command from comment
        COMMENT="${{ github.event.comment.body }}"
        COMMAND=$(echo "$COMMENT" | sed 's/@claude //')
        
        echo "Processing command: $COMMAND" > claude_output.md
        echo "" >> claude_output.md
        
        # Run Claude Code with the command
        claude-code assist \
          --prompt "$COMMAND" \
          --context "." \
          --output temp_result.md
        
        cat temp_result.md >> claude_output.md
        
        # Post response as PR comment
        gh pr comment ${{ github.event.issue.number }} --body-file claude_output.md
      env:
        GH_TOKEN: ${{ github.token }}
    
    - name: React to comment
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.reactions.createForIssueComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            comment_id: context.payload.comment.id,
            content: 'rocket'
          })